### ISSUE TITLE
Search issues.

### ISSUE THREAD

**Issue by Innomen** [ChrisNZL/Fauxbar#3]
It appears I've misunderstood this plugin completely. Is it not supposed to apply to the actual chrome address bar? If so I can't get it to work that way.

**Comment by ChrisNZL** [comment]
If you want to use Fauxbar's search methods from Chrome's address bar, you have to type **F**+**Space** before your query - this will activate Fauxbar within Chrome's address bar.

![image](https://cloud.githubusercontent.com/assets/280814/14969508/e112d8ce-1116-11e6-8d82-d350673769fa.png)

Unfortunately I can't override Chrome's way of doing things completely; am limited to what the Chrome extension API offers.

Fauxbar replaces Chrome's New Tab page with a mock address bar that appears below Chrome's address bar. (hence the name _fake bar_!)

Fauxbar Lite, on the other hand, leaves the New Tab page alone and requires you to either always use F+Space, or to click the Fauxbar icon on the toolbar to bring up the main Fauxbar page.

**Comment by Innomen** [comment]
I was afraid of that and commented somewhere to that effect. Well, thanks for doing what you canand answering, and making this. 

Curious, is this situation the same with Chromium?

**Comment by ChrisNZL** [comment]
Same, yeah.

Really, it's understandable for the Chromium team to lock down what you can and can't do, otherwise you'd get into the mess with how Internet Explorer used to be, with malicious plugins taking full control of everything to spite you.

A part of me wonders too if the Chrome address bar purposely gives you search suggestions amidst its half-baked history search to try and drive traffic to google.com :P

**Comment by Innomen** [comment]
No question. A gimped internal search bar is obviously designed to drive traffic to Google. That's made obvious by the spellchecking situation in chrome. Previously it was AWFUL and then they put in a Google spyware thing where your typos and stuff can goto google to get suggestions that make something approaching sense.

WTF is the point of an open source version of chrome if it's locked down?

Next silly question, how hard would it be to make/port this for/to firefox? Or some other browser that lets me replace the bar?

Total sidenote: I wish chrome had this: 
https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/
(Lazarus doesn't work like it at all.)

What browser do you use?

**Comment by ChrisNZL** [comment]
Anyone could in theory fork Chromium and change how it all works, but then you'd forever be playing catch-up with security updates and implementing new web/HTML features. I'm not a C++ programmer and such a task is out of my league.

I use Chrome. I only use Chrome because of Fauxbar though. Chrome's address bar infuriates me still. I don't like how Firefox feels... it was good back in the day, but Chrome came along and changed my tastes, apart from the address bar. Firefox's frecency address bar algorithm is superb. And so yeah, I made Fauxbar to try and keep me happy enough with Chrome. Fauxbar is not perfect, but I still believe it's better than Chrome's address bar.

Fauxbar's kept a steady 7,000-8,000 active users over the past few years, so it's certainly an issue (and desired solution) that is shared amongst some.

**Comment by Innomen** [comment]
Dude it's superb. It's just a shame that I can't drag the old bar out of the way like I can in firefox and replace it with your bar. I feel like I'm on a mac. Denied access like an adult putting the cookie jar on the fridge top. Deeply insulting of them. Everyone wants to be steve jobs when they grow up. Patent/steal all the vowels. >.<

Thanks again for making it. I guess this is as good as it gets.
