### ISSUE TITLE
Fauxbar Address Box matches “Error: URl malformed” text

### ISSUE THREAD

**Issue by seanryan-seanryan** [ChrisNZL/Fauxbar#35]
When typing characters in the Fauxbar Address Box, it returns hits for bookmarks marked “Error: URl malformed” (it matches on the substring “URl malformed”). So when I type “med”, it highlights all “URl malforMED”. Can you change this behaviour? 
PS: The “Error” bookmarks are those with embedded “%s” which are compatible with another Chrome extension that has the ability to substitute %s with address bar text provided as a search string.

Thanks for a brilliant extension!

**Comment by ChrisNZL** [comment]
Thanks for reporting both issues.

It seems Fauxbar's `urldecode` method is failing to parse the URL since `%s` is not a valid encoding character (eg doesn't match anything on [this HTML encoding list](http://krypted.com/utilities/html-encoding-reference/)).

I will likely investigate seeing if, in the event of it failing to decode, if returning the URL as is would work better.

**Comment by ChrisNZL** [comment]
Fixed in v1.8.0. Added a catch to just return the URL as is if the `URI malformed` error is encountered.
