### ISSUE TITLE
Slow to select items from certain drop-down lists

### ISSUE THREAD

**Issue by e14mattc** [ChrisNZL/Fauxbar#5]
I've noticed that Fauxbar is the reason it takes >6 seconds from selecting any options in the 2 drop-down menus on this site.. I tested this by enabling/disabling Fauxbar in Incognito mode.

https://products.avnet.com/shop/en/ema/capacitor/CategoryDisplay?catalogId=10001&defaultPageView=grid&urlLangId=-1&langId=-1&urlRequestType=Base&storeId=715839035&categoryId=3074457345616680172#facet=avn_norm_attrd_voltage_ac:63

![image](https://cloud.githubusercontent.com/assets/9819307/21762369/33a302cc-d650-11e6-9c08-273b545246dd.png)

I've not noticed it elsewhere, but now I know it's affecting that kind of thing, I'll be on the lookout for it on other sites.

**Comment by ChrisNZL** [comment]
That Package/Case dropdown contains 4,456 items, which is a lot. It takes about 1 second to load for me with Fauxbar running, but takes the same amount of time in Incognito without Fauxbar as well.

Fauxbar does a couple of jQuery things when hovering over parts of forms to do with Fauxbar's "Add as search engine" feature (checking the form to see if it's able to be used as a custom search engine), which might be causing some lag in this case since there are so many `option` elements within the drop-down that jQuery has to traverse.

**Comment by e14mattc** [comment]
Thanks @ChrisNZL  .. simply turning off that option in the Fauxbar settings has sorted it for me. Thanks for your work on this app.. much appreciated. I was a FF user moving to Chrome and really missed how the search found everything I wanted in FF; Fauxbar totally fixes that problem :)
