### ISSUE TITLE
Crashing / Corruption in Chrome 76

### ISSUE THREAD

**Issue by lins05** [ChrisNZL/Fauxbar#50]
First of all, thanks  for this amazing extension.

I'm using chrome beta, and after last chrome upgrade I find once a while fauxbar need to be fixed in the about:extension page. It would then work again for a while and broke again.

Here is my chrome version:
```
Version 76.0.3809.36 (Official Build) beta (64-bit)
```

**Comment by ChrisNZL** [comment]
Hey lins05, thanks for your kind words.

I'll try using Chrome Beta 76 today to see if I can reproduce any issues, but I haven't had any luck yet.

If you open:
```
chrome-extension://hibkhcnpkakjniplpfblaoikiggkopka/html/fauxbar.errorlog.html
```
are there any errors?

Additionally, if you go to:
1. `chrome://extensions/`
2. Enable "Developer mode" in the top-right corner
3. Under Fauxbar 1.8.1, click the "Inspect views background page" link

Any different errors there? (don't worry about any `Unchecked runtime.lastError: No tab with id: XXX` errors)

**Comment by lins05** [comment]
Hey @ChrisNZL , I tried to grab the error logs using your instructions, but the thing is each time the moment I realize the extension crashes, it became disabled/gray in the extensions page. 

I'll see if I can get the log by checking that page now and then.

**Comment by ChrisNZL** [comment]
Sounds like a tough one to get logs for.

Fauxbar has checks in place to see if its database is intact upon start.

If the extension is fully crashing and Fauxbar's WebSQL/SQLite database is getting corrupted, sounds semi related to [Fauxbar issue #48](https://github.com/ChrisNZL/Fauxbar/issues/48#issuecomment-499460678) where some sort of Chrome database file accessing/locking was recently going awry in Chrome 75.

Ultimately, this is probably another sign for me to [replace WebSQL (issue #49)](https://github.com/ChrisNZL/Fauxbar/issues/49).

**Comment by theSloopJohnB** [comment]
@lins05 - Did you have any luck resolving this issue? Now that Chrome 76 is the default, I'm running into this multiple times a day as well :(

@ChrisNZL - Totally understand if this can't be fixed right away. I love the extension, and it makes me realize how helpful it is when I have to go back to the default behavior.

**Comment by thischrisoliver** [comment]
I'm also having issues with Chrome 76. Fauxbar kept crashing, and in `chrome://extensions/`, Chrome said Fauxbar was corrupted and needed to be repaired. Clicking the Repair button made Fauxbar work again for a little while, but I lost all my settings, and it would quickly crash again. I ended up restoring Chrome 75 from a backup, and Fauxbar seems to be working fine again.

**Comment by ChrisNZL** [comment]
This is gonna be a tough one. I still haven't seen this myself on two different Windows installations, so can't properly debug 😬 

If Chrome 75 is still working, perhaps sticking with that version as a temporary solution could work if Fauxbar is a must-have. Not sure how to prevent Chrome from auto-updating though.

As mentioned previously, this is likely a WebSQL async regression with Chrome, and tackling [issue #49 (Replace WebSQL)](https://github.com/ChrisNZL/Fauxbar/issues/49) is probably still the way to go, but is not a simple task.

**Comment by thischrisoliver** [comment]
I don't know if it makes a difference, but I'm on a Mac.

**Comment by Talaaya** [comment]
This sounds like the same problem I'm having. It started happening very recently, after Chrome crashed and stopped working entirely, and I had to reinstall it.
The crash log has these types of errors for me:

Unchecked runtime.lastError: No tab with id: 500.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)

I can't get it to repro consistently on a particular action, it just seems to stop working sometimes after I've messed with settings (especially search engine settings) and then open a new tab.

Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by e14mattc** [comment]
Had this twice now since upgrading to Chrome 76. Repaired it earlier this week.. then suddenly it's corrupted again today, part way through the day (no reboots.. just working one minute, corrupt the next) :(

**Comment by pteyssier** [comment]
@ChrisNZL Have you contacted google support about it? I don't think it's a problem of corruption. 
I'm using mac also, and every couple of days, the same error appear, but i don't need to rebuild the index. Luckily, using "Repair" button does not work for me(for a known reason not important to mention here) so I have to go on https://chrome.google.com/webstore/detail/fauxbar/hibkhcnpkakjniplpfblaoikiggkopka and click "enable this item", which allow me to use again your extension without losing any configuration ( @thischrisoliver if this can help you ). 

So i suppose some security mechanism in Chrome is faulty and force-disable your extension on mac.

**Comment by ChrisNZL** [comment]
Regarding:
>Unchecked runtime.lastError: No tab with id: 500.

The `No tab with id` error in the background console has been around for a long time (way before these crashing issues came about). I believe I narrowed it down where, this error gets logged when Fauxbar attempts to do something with a Chrome tab, but the tab has been closed. Due to the asynchronous nature of Chrome's API calls, sometimes a tab closes before a call gets finished (especially when there's calls within calls). Probably could wrap various calls within a try/catch, but it just seems like a non-issue, just a warning rather than a hard error causing problems.

---

Regarding the crashing/corruption, it really sounds like a file-access issue with macOS.

The weird thing with WebSQL here, is that everything is transaction-based, so if a transaction fails, in theory the transaction should never get committed, and the database should remain intact.

But if the database is getting flat-out corrupted, this is something happening outside of Fauxbar. A regression with Chromium I'd say. Fauxbar does not access your filesystem directly; it has to use Chrome's APIs.

@pteyssier sounds like your Chrome is recognising a crash and shutting Fauxbar down before its WebSQL database file becomes corrupted for whatever reason.

I haven't contacted Google about this, as I would likely need to create a small reproducible test extension to submit, and I just haven't had the time, energy, nor motivation to do so. Would rather work on switching to IndexedDB instead. But with recent chronic health issues taking a toll on my day-to-day life, and my attempts to continue to pursue commercial endeavours as best I can to support my family without winding up on a disability benefit, Fauxbar - which is just a hobby project - is not a high priority in my life right now.

**Comment by e14mattc** [comment]
FYI, I'm on a Windows 7 PC, so it's not just a macOS issue.

**Comment by ChrisNZL** [comment]
Ah dang. Windows 10 is my main computer. I don't have Windows 7 installed anywhere at the moment. I don't use macOS much in my day-to-day tasks either.

Just thinking - if you'd be willing to try...
On https://github.com/ChrisNZL/Fauxbar/releases, try downloading **Fauxbar_1.8.0.zip**, extract to a folder, go to `chrome://extensions`, disable Fauxbar, enable developer mode, then click the <kbd>Load unpacked</kbd> button, and choose the extracted folder.

In the Fauxbar 1.8.1 commit, I wrote:
> Fixes issue #48 - common.js' openDb method now uses the background page's window.db var for all tabs.

The `common.js` file change can be seen [here](https://github.com/ChrisNZL/Fauxbar/commit/683827d90b5f5a7319635c1b045f510fcf1f261f#diff-7a0e6c875faa7f3e7e5c46adbf85f4cb). Basically making the extension always use the background page's database connection, rather than establishing new connections all the time.

But perhaps this change is an issue. Yet it was all an attempt to fix [issue #48](https://github.com/ChrisNZL/Fauxbar/issues/48).

I've made a Dropbox folder containing older versions: [Fauxbar versions - public archive](https://www.dropbox.com/sh/vl543472qfos8m7/AAA53Oykh0pL5nevQ7ovcb6Ma?dl=0&lst=)
Maybe try the **Fauxbar 1.7.3.zip** version to see if things still crash or not?

---

Thinking out loud, I'm also wondering if having tabs set `window.db` to the `getBackgroundPage().db` variable is triggering some kind of caching issue, like maybe if the background page is getting reset or refreshed, and there's some kind of out-of-date var mismatch happening at times.

But if Chrome 75 introduced the inability to have multiple tabs access their `window.db` var via the `openDatabase` method due to concurrency/async issues with WebSQL (a regression with Chrome), and Chrome 76 is further not liking async access...

When tackling issue #48, I did do a multi-file change at one point, but then condensed the change into common.js' `openDb` method, but maybe trying this again would be prudent: https://github.com/ChrisNZL/Fauxbar/issues/48#issuecomment-501660743
>I've replaced all instances of `window.db` with `chrome.extension.getBackgroundPage().db` and it seems to have resolved the locking errors.

So maybe I should make a test version of this again to see if it helps. Let me see if I can get it going.

**Comment by e14mattc** [comment]
Happy to try whatever fixes you want. I saw there's a 1.8.1 version and 1.8.0.. which would you like me to download & run?

**Comment by ChrisNZL** [comment]
@e14mattc Please try the [1.8.0](https://github.com/ChrisNZL/Fauxbar/releases/tag/v1.8.0), but if that crashes, try the [1.7.3](https://www.dropbox.com/sh/vl543472qfos8m7/AAA53Oykh0pL5nevQ7ovcb6Ma?dl=0&lst=).

**Comment by e14mattc** [comment]
1.8.0 isn't happy.. it pops up this each time I load a new tab. Rebuilding the d/b doesn't make any difference.

![image](https://user-images.githubusercontent.com/9819307/64158416-55845a00-ce30-11e9-9f03-485ae2b19173.png)

1.7.3 gives the same error.

**Comment by ChrisNZL** [comment]
Thanks for trying both. So 1.8.1’s change of accessing the background
page’s database connection is definitely a requirement still.

I will be keen to try the `getBackgroundPage` replace-all next. I’m away on
a business trip for a few days, so might be a while, but I’ll try to get a
test version available up when possible.

**Comment by e14mattc** [comment]
Hmm, since upgrading to Chrome 78 & adding my tiles back in I've not had this problem with v1.8.1. Crossing my fingers...!! :crossed_fingers:

**Comment by theSloopJohnB** [comment]
Seems to be working for me too. I've been using it for 2 days without an
issue, usually by now it has become corrupted.

**Comment by lins05** [comment]
This problem has not happened during the last two months. Thanks again @ChrisNZL !  Closing.
