### ISSUE TITLE
How to build Fauxbar from source code?

### ISSUE THREAD

**Issue by clarkwang** [ChrisNZL/Fauxbar#69]
Trying to fix #68 since it looks quite simple but I'm not a web developer and don't know how to build the extension from source. Any instructions?

**Comment by ChrisNZL** [comment]
1. Click the green <kbd>Code</kbd> button and grab a copy of the Fauxbar repo (or fork it). I like using [GitHub Desktop](https://desktop.github.com/). Or download the ZIP file of the repo and extract to somewhere.

![image](https://user-images.githubusercontent.com/280814/151035578-c1f9dc51-2b4e-4b5b-98fe-0953f2c78f71.png)

2. In Chrome, open `chrome://extensions/`.

3. Disable your current `Fauxbar` or `Fauxbar Lite` extension.

3. Enable `Developer mode` in the top-right.

4. Click the <kbd>Load unpacked</kbd> button.

5. Navigate to the directory where you saved or extracted the repo, and choose the `Fauxbar\Fauxbar` folder. Fauxbar will then show its icon but have a red/orange icon overlapping it, signifying it's an "unpacked" extension.

6. Edit the scripts as desired. Depending on what you're editing, sometimes you can refresh a page with <kbd>Ctrl</kbd>+<kbd>R</kbd> to load the changes; otherwise you'll need to click the 🔄 (reload/refresh) icon to reload the entire extension:
![image](https://user-images.githubusercontent.com/280814/151036938-48931982-c5a4-4c1c-9eec-b6ebbf2c66dd.png)

7. If you need to test Fauxbar Lite specifically, check out the `////` comments within [manifest.json](https://github.com/ChrisNZL/Fauxbar/blob/master/Fauxbar/manifest.json).

**Comment by clarkwang** [comment]
Cool it does not need to be built. `*<space>` in address box is now working. Thanks!
